apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safevoice

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: safevoice

images:
  - name: ghcr.io/safevoice009/safevoice
    newTag: latest
